export const mainTheme = {
  token: {
    fontFamily: "Poppins, sans-serif",
  },
  components: {
    Menu: {
      colorPrimary: "#ffffff",
      iconSize: 24,
      itemActiveBg: "#AA8FFF",
      itemActiveColor: "#ffffff",
      itemHoverColor: "#2c2c2c",
      itemColor: "#667085",
      itemSelectedBg: "#AA8FFF",
      itemSelectedColor: "#ffffff",
      iconColor: "#2c2c2c",
      subMenuItemBg: "#ffffff",
    },
    Form: {
      colorError: "#E53935",
    },
    Checkbox: {
      colorPrimary: "#AA8FFF",
      colorPrimaryHover: "#AA8FFF",
    },
    Select: {
      colorTextQuaternary: "#2c2c2c",
      colorBgContainer: "rgba(0,0,0,0)",
      fontSize: 18,
      optionSelectedColor: "#ffffff",
      optionSelectedBg: "#AA8FFF",
      optionActiveBg: "#AA8FFF33",
      optionActiveColor: "#ffffff",
      colorBorder: "#ffffff",
      colorBgElevated: "#efefef",
      selectorBg: "#efefef",
      colorText: "#2c2c2c",
      colorTextPlaceholder: "#2c2c2c88",
      hoverBorderColor: "#fff",
      colorIcon: "#AA8FFF",
    },
    DatePicker: {
      colorTextQuaternary: "#2c2c2c",
      fontSize: 18,
      colorTextPlaceholder: "#2c2c2c88",
      colorBgElevated: "#ffffff",
      colorText: "#2c2c2c",
      colorTextHeading: "#2c2c2cBB",
      colorTextDisabled: "#2c2c2c33",
      colorIcon: "#2c2c2c",
      colorIconHover: "#2c2c2c",
      colorPrimary: "#AA8FFF",
    },
    timePicker: {
      fontSize: 20,
      colorTextPlaceholder: "#D0D5DD",
      colorBgElevated: "#202020",
      colorText: "#2c2c2c",
      colorTextHeading: "#2c2c2cBB",
      colorTextDisabled: "#2c2c2c33",
      colorIcon: "#2c2c2c99",
      colorIconHover: "#2c2c2c",
      colorPrimary: "rgb(27,27,27)",
    },
    Upload: {
      colorTextQuaternary: "#2c2c2c",
      colorFillAlter: "rgba(0,0,0,0)",
      colorBorder: "#2c2c2c",
      colorBorderHover: "#2c2c2c",
      colorText: "#2c2c2c",
      colorIcon: "#2c2c2c",
      actionsColor: "rgba(255,0,0)",
    },
    Table: {
      headerBg: "#ffffff",
      colorBgContainer: "#ffffff",
      colorText: "#2c2c2c",
      colorIcon: "#2c2c2c",
      borderColor: "#2c2c2c44",
      headerColor: "#2c2c2c",
      fontSize: 16,
      footerColor: "#FDFDFD",
      // marginXXS: 4,
      colorLinkActive: "#FDFDFD",
      headerSplitColor: "#2c2c2c22",
      headerFilterHoverBg: "#2c2c2c99",
    },
    Pagination: {
      colorBgContainer: "#ffffff",
      itemActiveBg: "#AA8FFF",
      itemActiveColor: "rgb(255,255,255)",
      colorPrimary: "rgb(255,255,255)",
      colorText: "#AA8FFF",
      colorBgTextHover: "#AA8FFF22",
    },
    Input: {
      colorTextPlaceholder: "##D0D5DD99 ",
      colorIcon: "#202020",
    },
    Radio: {
      colorPrimary: "#6A0DAD",
      colorPrimaryHover: "#6A0DAD",
    },
    Modal: {
      contentBg: "#ffffff",
      headerBg: "#ffffff",
      colorIcon: "#2c2c2c",
      colorIconHover: "#2c2c2c",
    },
    Rate: {
      starBg: "#2c2c2c66",
    },
  },
};
